### ISSUE TITLE
node-gyp rebuild fails on Catalina: error: no viable conversion from 'MaybeLocal<v8::String>' to 'Local<v8::String>'

### ISSUE THREAD

**Issue by artsra** [jkuri/macstats#10]
```
% npm install -g macstats
/usr/local/bin/macstats -> /usr/local/lib/node_modules/macstats/bin/macstats

> macstats@2.2.0 install /usr/local/lib/node_modules/macstats
> node-gyp rebuild

  CXX(target) Release/obj.target/smc/smc/smc.o
../smc/smc.cc:272:9: error: no viable conversion from 'MaybeLocal<v8::String>' to 'Local<v8::String>'
        String::NewFromUtf8(isolate, "Expected number")));
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/artsr/Library/Caches/node-gyp/13.2.0/include/node/v8.h:189:7: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from
      'MaybeLocal<v8::String>' to 'const v8::Local<v8::String> &' for 1st argument
class Local {
      ^
/Users/artsr/Library/Caches/node-gyp/13.2.0/include/node/v8.h:189:7: note: candidate constructor (the implicit move constructor) not viable: no known conversion from
      'MaybeLocal<v8::String>' to 'v8::Local<v8::String> &&' for 1st argument
/Users/artsr/Library/Caches/node-gyp/13.2.0/include/node/v8.h:193:13: note: candidate template ignored: could not match 'Local' against 'MaybeLocal'
  V8_INLINE Local(Local<S> that)
            ^
/Users/artsr/Library/Caches/node-gyp/13.2.0/include/node/v8.h:6995:47: note: passing argument to parameter 'message' here
  static Local<Value> TypeError(Local<String> message);
                                              ^
../smc/smc.cc:275:39: error: too few arguments to function call, single argument 'context' was not specified
  int fanNumber = args[0]->Int32Value();
                  ~~~~~~~~~~~~~~~~~~~ ^
/Users/artsr/Library/Caches/node-gyp/13.2.0/include/node/v8.h:2778:3: note: 'Int32Value' declared here
  V8_WARN_UNUSED_RESULT Maybe<int32_t> Int32Value(Local<Context> context) const;
  ^
/Users/artsr/Library/Caches/node-gyp/13.2.0/include/node/v8config.h:419:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../smc/smc.cc:282:6: error: variable has incomplete type 'void'
void Init(v8::Handle<Object> exports)
     ^
../smc/smc.cc:282:15: error: no member named 'Handle' in namespace 'v8'
void Init(v8::Handle<Object> exports)
          ~~~~^
../smc/smc.cc:282:22: error: 'Object' does not refer to a value
void Init(v8::Handle<Object> exports)
                     ^
/Users/artsr/Library/Caches/node-gyp/13.2.0/include/node/v8.h:3541:17: note: declared here
class V8_EXPORT Object : public Value {
                ^
../smc/smc.cc:282:30: error: use of undeclared identifier 'exports'
void Init(v8::Handle<Object> exports)
                             ^
../smc/smc.cc:282:38: error: expected ';' after top level declarator
void Init(v8::Handle<Object> exports)
                                     ^
                                     ;
7 errors generated.
make: *** [Release/obj.target/smc/smc/smc.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
gyp ERR! System Darwin 19.2.0
gyp ERR! command "/usr/local/Cellar/node/13.2.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/macstats
gyp ERR! node -v v13.2.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! macstats@2.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the macstats@2.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/artsr/.npm/_logs/2020-01-15T10_52_24_826Z-debug.log
```

**Comment by CrashOverride90** [comment]
Same issue for me as well

**Comment by Athuli7** [comment]
Same here
